### ISSUE TITLE
Make Main Menu Togglable

### ISSUE THREAD

**Issue by ForBai** [cornos/Atomic#22]
Show Title

**Comment by 0x150** [comment]
next update

**Comment by ForBai** [comment]
do you also update to 1.17.1?

**Comment by 0x150** [comment]
its on 1.17.1 already?

**Comment by ForBai** [comment]
when you mean atomic no its not on 1.17.1 only 1.17
but minecraft already is on 1.17.1

**Comment by 0x150** [comment]
put the atomic jar into 1.17.1 and be amazed

**Comment by ForBai** [comment]
ok

**Comment by ForBai** [comment]
how?

**Comment by 0x150** [comment]
just take 1.17.1 fabric

and put the latest.jar into the mods folder

**Comment by ForBai** [comment]
i mean how did you make that a 1.17 mod works in 1.17.1?
like code i meant

**Comment by 0x150** [comment]
a mod can be compatible with many versions at once

**Comment by Nusshundeart24** [comment]
holy shit this made me lose a few braincells that i didnt know existed
