### ISSUE TITLE
XRay not showing Ancient Debris

### ISSUE THREAD

**Issue by epixinvites** [cornos/Atomic#25]
I tried using the XRay with the original Minecraft texture pack, but the Ancient Debris weren't showing up, I had to switch to a custom XRay texture pack before the Debris showed up. Is this an intended feature or a bug?

Plus, I suggest that you should let us set what ores to show via XRay, sometimes we just need to find Diamonds and Debris rather than every single type of ore.

**Comment by 0x150** [comment]
fixed a while ago, update the client stinky
