### ISSUE TITLE
c

### ISSUE THREAD

**Issue by xiaofengv233** [cornos/Atomic#26]
Stuck here all the time
![屏幕截图(3)](https://user-images.githubusercontent.com/24617660/126022944-cb9a37de-4a3f-4287-be68-c8f2fbbe1a29.png)

**Comment by 0x150** [comment]
how good is your internet

**Comment by xiaofengv233** [comment]
> how good is your internet

10m/s

**Comment by 0x150** [comment]
I can make it time out after a specific amount of time spent, but what its doing is basically downloading the latest file to check for updates

**Comment by 0x150** [comment]
i'll make it time out, but you'll have to check for updates yourself :/
