### ISSUE TITLE
[Bug] No backdoored 😢 

### ISSUE THREAD

**Issue by erxdev** [cornos/Atomic#28]
**Describe the bug**
No backdoored 😢

**To Reproduce**
Steps to reproduce the bug:
1. Backdoor it

**Expected behavior**
No backdoored 😢

**What actually happened**
No backdoored 😢

**Screenshots**
No

**Additional context**
No backdoored 😢

**Comment by timof121** [comment]
😭

**Comment by 0x150** [comment]
:trollface:

**Comment by h4rmy** [comment]
now this is funny
