### ISSUE TITLE
[Suggestion] OreSim from Cornos

### ISSUE THREAD

**Issue by erxdev** [cornos/Atomic#3]
Mr. 19MisterX98, please.

**Comment by 19MisterX98** [comment]
I'll do it when I have time (maybe next weekend?). Might actually also implement baritone Automine.

**Comment by feliscatusmeows** [comment]
pog baritoneXoresim

**Comment by Tiebe** [comment]
>  Might actually also implement baritone Automine.
Yeeesss that would be awesome!

**Comment by Nusshundeart24** [comment]
indeed
