### ISSUE TITLE
Oresim dont render 

### ISSUE THREAD

**Issue by hiperion14** [cornos/Atomic#33]
Oresim dont renders in the survival world but it works perfectly in other worlds

**Comment by 0x150** [comment]
can i get a screenshot comparing the 2?

**Comment by hiperion14** [comment]
**SERVER SPAWN WORLD**
![2021-07-22_10 25 42](https://user-images.githubusercontent.com/35075594/126610143-0ba07378-e03c-42a4-8f38-17c88c92fc70.png)
**SERVER SURVIVAL WORLD**
![2021-07-22_10 25 52](https://user-images.githubusercontent.com/35075594/126610168-63ce7286-74e7-418f-a1e0-2e3035e0be2b.png)

**Comment by 19MisterX98** [comment]
Seems like the overworld was renamed to world. That messes with dimension detection. Should be fixable

**Comment by hiperion14** [comment]
> Seems like the overworld was renamed to world. That messes with dimension detection. Should be fixable

It can be fixed by detecting the dimension with the biome, right?

**Comment by 0x150** [comment]
oresim isnt actually my part, 19 should be able to fix it
