### ISSUE TITLE
no keol gui

### ISSUE THREAD

**Issue by AcaiBerii** [cornos/Atomic#38]
**Describe the bug**
A description of what the bug is
keol concept gui when

**To Reproduce**
Steps to reproduce the bug:
1: you didnt implement keol gui

**Expected behavior**
implementation of keol gui

**What actually happened**
no implement keol gui

**Screenshots**
no

**Additional context**
keol gui now

**Final checklist**
- [ ] This is an issue with an older version of the client
- [x] I have tried to reproduce this with every other mod removed
- [x] I am on java 16 and minecraft 1.17

**Comment by 0x150** [comment]
send me a screenshot of the keol gui and maybe ill add it

**Comment by 0x150** [comment]
alr then

**Comment by AcaiBerii** [comment]
> alr then

![wtf](https://i.imgur.com/RqHkwuG.png)

was this not you?

**Comment by 0x150** [comment]
i need a clickgui prototype to actually make a clickgui theme yknow

**Comment by AcaiBerii** [comment]
Oh
