### ISSUE TITLE
Can't move once we open inventory.

### ISSUE THREAD

**Issue by devendrapoonia** [cornos/Atomic#39]
Hello,
There is a issue in Atomic client. After launching the client, everything will work fine, but if I once open inventory by pressing E.
I will stuck forever, client don't let me move. it just stuck me at one place. to fix this i have to reset my moving keys everytime and it is so annoying.
Please fix this.

**Comment by devendrapoonia** [comment]
My Fabric version - 0.11.6
Mods in my mods folder - latest.jar, fabric-api-0.40.0+1.17.jar
Game version - 1.17.1

**Comment by 0x150** [comment]
which modules did you enable

**Comment by devendrapoonia** [comment]
I enabled only ore sim. and this happen always with me. I also faced this issue with cornos, with in cornos if use panic issue will resolve with in cornos. But it doesn't work in Atomic.

**Comment by 0x150** [comment]
seems like a you issue ngl

**Comment by devendrapoonia** [comment]
??

**Comment by devendrapoonia** [comment]
Please fix this.

**Comment by 0x150** [comment]
> ??

never happened with anyone else, and the issue seems very specific. i have no idea what could cause this, there is nothing in my code that would block you from moving when you open your inventory

**Comment by devendrapoonia** [comment]
I am also think so. I don't know what's happening.

**Comment by devendrapoonia** [comment]
btw is there any way to disable updates when we launch. and we can manually update later. because most of the time, I play offline.

**Comment by devendrapoonia** [comment]
Anyway I am uinstalling mc, and I will reinstall. There are a lot of issues in it. Entire game is broke.

**Comment by 0x150** [comment]
im gonna close this for now, tell me if its fixed or not if you can
