### ISSUE TITLE
Minercraft Crash

### ISSUE THREAD

**Issue by AmmarImran04** [cornos/Atomic#41]
Minecraft did not start due to an unknown error! Probably it happened for your mods, try to delete it or read below 
 You have installed mods. We advise you to assemble your assembly using our mod-pack system link 
   How it helps!  
  1) If the game breaks (crashes) with your mods, then turn off all the mods (click on the green box to the right of the installed mod) and launch the launcher (to make sure that the empty build works ), then activate (click on the gray box) a few pieces or one and start the game, so you will understand at what point the problem arises.
  2) Make backups of your working assemblies. 
  3) Send your friends with builds.
  
  above is what i am getting when is use the latest.jar file if i remove it its working better 
I really need a help fixing this please

**Comment by 0x150** [comment]
what kinda launcher are you using bruh

**Comment by DamnUi** [comment]
hes using tlaucher

**Comment by 0x150** [comment]
then its probably that

**Comment by devendrapoonia** [comment]
Same happening with me.

**Comment by devendrapoonia** [comment]
Same error message shows to me. and I also use tlauncher. If I remove mod from folder, everything works fine.

**Comment by devendrapoonia** [comment]
i hope the issue will be fixed soon.

**Comment by DamnUi** [comment]
show me your mod folder, i think i know how to fix
