### ISSUE TITLE
.unload command

### ISSUE THREAD

**Issue by feliscatusmeows** [cornos/Atomic#6]
add a .unload command that disables all modules and keybinds, and sets the prefix to unicode 😬, sets the title and icon to vanilla, spoofs the f3 to look like a regular fabric install and does other stuff

**Comment by 0x150** [comment]
issue: you cant really do that with fabric

**Comment by maxappsteam** [comment]
Just make sure to add panic that disabled all modules

**Comment by feliscatusmeows** [comment]
Yea, so I suggested that it try to disable cornos as much as possible

**Comment by feliscatusmeows** [comment]
frick I mean atomic, pretend I said atomic

**Comment by 0x150** [comment]
yea doing that some time
