### ISSUE TITLE
.itemstorage does nothing except saving text

### ISSUE THREAD

**Issue by h4rmy** [cornos/Atomic#62]
also ur lawyer said that u need to fix that so do it pls thanks
https://youtu.be/JHN1BGiAD-I

**Comment by 0x150** [comment]
do you have multiconnect

**Comment by h4rmy** [comment]
> do you have multiconnect

is it the reason why it happening? yes i do have it installed

**Comment by 0x150** [comment]
remove multiconnect and get viafabric
