### ISSUE TITLE
nice rat

### ISSUE THREAD

**Issue by master7720** [cornos/Atomic#63]

**Comment by h4rmy** [comment]
dont use then

**Comment by h4rmy** [comment]
dude ur github is all rats all over it without any obfuscation and revealed discord webhook

**Comment by 0x150** [comment]
duper fanboy?

**Comment by master7720** [comment]
XD i warn ppl if theres rats in my stuff unlike 0x150

**Comment by 0x150** [comment]
> XD i warn ppl if theres rats in my stuff unlike 0x150

duper fanboy
